In [1]:
import numpy as np
a=[1,2,3,4]
b=np.array(a)
type(b)
b.shape
b.argmax()#最大值的坐标
b.max()
b.mean()

numpy.ndarray

In [7]:
c=[[1,2],[3,4]]
d=np.array(c)
d.size
print(d)
print(d.max(axis=0))#纵轴方向上的最大值
print(d.max(axis=1))#横轴方向上的最大值
print(d.flatten())#展看一个numpy数组为1维数组
np.save('d.npy',d)#保存到文件
d1=np.load('d.npy')#从文件读取

[[1 2]
 [3 4]]
[3 4]
[2 4]
[1 2 3 4]


In [14]:
e=np.repeat(3,4)#创建一个一维数组，元素值是把3重复4次
print(e)

[3 3 3 3]


In [13]:
f=np.linspace(0,6,5)#等差数列，0到6之间取5个值
print(f)

[ 0.   1.5  3.   4.5  6. ]


In [12]:
g=np.split(np.arange(9),3)#平均分成3份
h=np.split(np.arange(9),[2,-3])#按下标位置划分
print(g)
print(h)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1]), array([2, 3, 4, 5]), array([6, 7, 8])]


In [15]:
a=np.abs(-1)
b=np.sin(np.pi/2)
c=np.arctanh(0.462118)#
d=np.exp(3)#e^3
f=np.power(2,3)#2的3次方
g=np.dot([1,2],[3,4])#点积
h=np.sqrt(25)#开方
l=np.sum([1,2,3,4])
m=np.mean([4,5,6,7])
n=np.std([1,2,3,2,1,3,2,0])#标准差

In [18]:
a=range(1,5)#均可以用于迭代，区别：返回的类型不一样
b=np.arange(1,5)
c=tuple(a)
d=list(a)
print(type(a))
print(type(b))
print(type(c))
print(type(d))

<class 'range'>
<class 'numpy.ndarray'>
<class 'tuple'>
<class 'list'>


In [20]:
a=np.array([3,4])
b=np.linalg.norm(a)
'''
用法：norm(x, ord=None, axis=None, keepdims=False)求范数( 向量的度量)
ord=1,2,np.inf(一范数，二范数，无穷范数)默认二范数
一范数：向量每个值的绝对值的和
二范数：向量每个值的平方和的开方
无穷范数：向量每个值的绝对值的最大值
'''
b#b的值等于根号下3^2+4^2

5.0

In [24]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.array([1,0,1])
np.dot(b,c)
np.trace(b)#矩阵的迹
np.linalg.det(b)#矩阵的行列式
np.linalg.matrix_rank(b)#矩阵的秩
e=np.array([[1,2],[3,4]])
U,s,V=np.linalg.svd(e)#对矩阵进行SVD分解
s

array([ 5.4649857 ,  0.36596619])

In [29]:
import numpy.random as random
random.seed(42)
n_tests=10000#实验次数
winning_doors=random.randint(0,3,n_tests)#生成每次实验的奖品所在的门的编号
change_mind_wins=0#换门中奖的次数
insist_wins=0#坚持中奖的次数
for winning_door in winning_doors:#winning_door中奖门的编号
    first_try=random.randint(0,3)#随机挑选一扇门
    remaining_choices=[i for i in range(3) if i !=first_try]#其它门的编号
    wrong_choices=[i for i in range(3) if i !=winning_door]#没有奖品门的编号
    if first_try in wrong_choices:#一开始选择没有奖品的门
        wrong_choices.remove(first_try)#没有奖品的门去除1个
    screened_out=random.choice(wrong_choices)#主持人打开没有奖品门中的一个
    remaining_choices.remove(screened_out)#剩余可选择的门去除主持人打开的一个
    changed_mind_try=remaining_choices[0]#如果改变选择，可选择的只剩一个
    change_mind_wins +=1 if changed_mind_try==winning_door else 0#
    insist_wins +=1 if first_try==winning_door else 0
print('you win{1} out of {0} tests if you changed your mind\n'
     'you win {2} out of {0} tests if you insist on the initial choice'.format(
     n_tests,change_mind_wins,insist_wins))

you win6616 out of 10000 tests if you changed your mind
you win 3384 out of 10000 tests if you insist on the initial choice
